### ISSUE TITLE
Errors in Swift 3 & Xcode 8

### ISSUE THREAD

**Issue by resand** [SzabZappDesigntemplates/ZDT-CustomProgressBarDelegate#1]
Errors
<img width="1392" alt="captura de pantalla 2016-10-12 a la s 9 22 24 p m" src="https://cloud.githubusercontent.com/assets/5307015/19334510/fe19dbd6-90c1-11e6-833b-9dd592ad2347.png">

**Comment by szabolcssztanyi** [comment]
Fixed, see last commit.
